name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    env:
      PYTHONPATH: src:test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          options: -v $GITHUB_WORKSPACE:/mnt -e ABC=123
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: add .env
        run: |
          touch .env
          echo ENVIRONMENT=local >> .env
          echo PYTHONPATH=src:test >> .env
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
              ${{ runner.os }}-venv-
      - run: python3 -m venv venv && . venv/bin/activate &&
          pip install -r requirements-dev.txt
        env:
          PYTHONPATH: src:test
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - name: lint
        run: |
          . venv/bin/activate
          flake8 ./test config.py
      - name: tests
        run: |
          . venv/bin/activate
          python -m pytest test/ --import-mode=importlib
